### ISSUE TITLE
Task Tracker

### ISSUE THREAD

**Issue by Kh4lil** [Kh4lil/MyAgenda.io#2]
**This issue is to keep track of what has and needs to be done on this project. Will be editing this to reflect the work progress:** 
- [ ] Design landing page
- [ ] HTML for landing page
- [ ] CSS for landing page
- [ ] Design Sign in page 
- [ ] HTML for Sign in page
- [ ] CSS for sign in page
- [ ] Design project tracker page
- [ ] HTML for tracker page
- [ ] CSS for tracker page
- [ ] Add JS to have a working tracker page
